### ISSUE TITLE
Cant install cordova plugin

### ISSUE THREAD

**Issue by cgarnier** [arcoirislabs/mqtt-cordova#2]
Hello, i cant install your plugin.

$ cordova plugin add com.arcoirislabs.plugin.mqtt
Fetching plugin "com.arcoirislabs.plugin.mqtt" via plugin registry
Installing "com.arcoirislabs.plugin.mqtt" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.arcoirislabs.plugin.mqtt':Error: Uh oh!
"d:\DEV\proj\WEB_MOBILITY\demoAc\plugins\com.arcoirislabs.plugin.mqtt\src\a
ndroid\Mqtt.java" not found!
    at Object.module.exports.common.copyFile (c:\npm\node_modules\cordova\node_m
odules\cordova-lib\src\plugman\platforms\common.js:43:40)
    at Object.module.exports.common.copyNewFile (c:\npm\node_modules\cordova\nod
e_modules\cordova-lib\src\plugman\platforms\common.js:60:16)
    at module.exports.source-file.install (c:\npm\node_modules\cordova\node_modu
les\cordova-lib\src\plugman\platforms\android.js:51:20)
    at Object.ActionStack.process (c:\npm\node_modules\cordova\node_modules\cord
ova-lib\src\plugman\util\action-stack.js:70:25)
    at handleInstall (c:\npm\node_modules\cordova\node_modules\cordova-lib\src\p
lugman\install.js:560:20)
    at c:\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.
js:320:20
    at _fulfilled (c:\npm\node_modules\cordova\node_modules\q\q.js:798:54)
    at self.promiseDispatch.done (c:\npm\node_modules\cordova\node_modules\q\q.j
s:827:30)
    at Promise.promise.promiseDispatch (c:\npm\node_modules\cordova\node_modules
\q\q.js:760:13)
    at c:\npm\node_modules\cordova\node_modules\q\q.js:574:44
Error: Uh oh!
"d:\DEV\proj\WEB_MOBILITY\demoAc\plugins\com.arcoirislabs.plugin.mqtt\src\a
ndroid\Mqtt.java" not found!
    at Object.module.exports.common.copyFile (c:\npm\node_modules\cordova\node_m
odules\cordova-lib\src\plugman\platforms\common.js:43:40)
    at Object.module.exports.common.copyNewFile (c:\npm\node_modules\cordova\nod
e_modules\cordova-lib\src\plugman\platforms\common.js:60:16)
    at module.exports.source-file.install (c:\npm\node_modules\cordova\node_modu
les\cordova-lib\src\plugman\platforms\android.js:51:20)
    at Object.ActionStack.process (c:\npm\node_modules\cordova\node_modules\cord
ova-lib\src\plugman\util\action-stack.js:70:25)
    at handleInstall (c:\npm\node_modules\cordova\node_modules\cordova-lib\src\p
lugman\install.js:560:20)
    at c:\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.
js:320:20
    at _fulfilled (c:\npm\node_modules\cordova\node_modules\q\q.js:798:54)
    at self.promiseDispatch.done (c:\npm\node_modules\cordova\node_modules\q\q.j
s:827:30)
    at Promise.promise.promiseDispatch (c:\npm\node_modules\cordova\node_modules
\q\q.js:760:13)
    at c:\npm\node_modules\cordova\node_modules\q\q.js:574:44

**Comment by CarlLee** [comment]
Mqtt.java is probably a mqtt client library, possibly from the Eclipse Paho project.

**Comment by arcoirislabs** [comment]
This is a very old plugin which is not compatible with latest versions of cordova. It was an experimental build but never got completed. We are really sorry for the inconvenience.
We are working on a new build

**Comment by Xplorer001** [comment]
Is it fixed? If so what needs to be done to apply the fix?
